-- MySQL Script generated by MySQL Workbench
-- Mon Sep 25 11:08:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema crossover
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `crossover` ;

-- -----------------------------------------------------
-- Schema crossover
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crossover` DEFAULT CHARACTER SET utf8 ;
USE `crossover` ;

-- -----------------------------------------------------
-- Table `crossover`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crossover`.`users` ;

CREATE TABLE IF NOT EXISTS `crossover`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `email` TEXT NULL DEFAULT NULL,
  `password` LONGTEXT NULL DEFAULT NULL,
  `remember_token` LONGTEXT NULL DEFAULT NULL,
  `active` TINYINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crossover`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crossover`.`news` ;

CREATE TABLE IF NOT EXISTS `crossover`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(80) NULL DEFAULT NULL,
  `text` LONGTEXT NULL DEFAULT NULL,
  `photo` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deteled_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_news_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_news_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `crossover`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
